# Generated by Django 5.2.5 on 2025-10-10 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0002_rename_appointment_appoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='date',
            field=models.DateField(default=datetime.date(2025, 10, 10)),
            preserve_default=False,
        ),
    ]
