# Generated by Django 5.2.5 on 2025-10-11 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0003_appoint_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appoint',
        ),
    ]
