# Generated by Django 5.2.5 on 2025-08-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=0.0)),
                ('image', models.ImageField(upload_to='services/')),
                ('category', models.CharField(choices=[('traditional', 'Traditional'), ('premium', 'Premium'), ('express', 'Express')], default='traditional', max_length=20)),
                ('features', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
