# Generated by Django 5.2.5 on 2025-10-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pleats', '0003_remove_appointment_email_remove_appointment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
